### PR TITLE
Allow for specifying datasets instead of pools

### PR DESCRIPTION
**Pull request by Freaky**
Also add a -n flag for non-recursive operation, showing only the
specific datasets requested.

This is an alternative to #10 which supports globbing.

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@adriaandegroot , would you mind taking a look at this? I like the idea for sure.

**Comment by jimsalterjrs** [comment]
@Freaky this is going to need to be rebased since I already merged your FreeBSD implementation. Thanks!

**Comment by Freaky** [comment]
@jimsalterjrs Cheers, just done so.

**Comment by jimsalterjrs** [comment]
@Freaky we're running pretty fast and furious right now; I went ahead and accepted the PR--can you please download the current master (including this and a couple other changes) and verify everything seems to be working properly?

If you've only got FreeBSD readily available, that'll do and I can check Linux tomorrow-ish. If you (or anybody else) can check both, that would be AMAZING and please comment after testing.

**Comment by Freaky** [comment]
Looks good to me on both FreeBSD 13 and Ubuntu 21.10.

**Comment by jimsalterjrs** [comment]
Thank you! Hopefully you tested after ALL the stuff I just merged. :)

**Pull request merged**
