### PR TITLE
Add a FreeBSD impl

### PR DESCRIPTION
**Pull request by Freaky**
Started this before I saw @adriaandegroot's work, oh well.

It could do with some tidying, but it appears to work.

### CODE REVIEW

**Comment by adriaandegroot** [comment]
You fixed the shebang, that's something I totally missed, and I didn't know about py-sysctl (nor, in my last PR, about `time.monotonic_ns()` so I'm going to steal that).

**Comment by jimsalterjrs** [comment]
Do we have any kind of consensus on whose patches I should be merging? I haven't looked super closely yet, but it sounds like you're both taking separate approaches to the same goal.

**Comment by adriaandegroot** [comment]
> Do we have any kind of consensus on whose patches I should be merging? I haven't looked super closely yet, but it sounds like you're both taking separate approaches to the same goal.

I think @Freaky is putting a little more effort here, and has covered several edge cases better. Looking at our different approaches, I'm into class hierarchies and defining code for all targets, and then subbing in types and functions as appropriate; he defines only things for the current platform, with no class hierarchy. To me, his code looks un-idiomatically terse, but cool (like the way to get `*fields` out of the contents of one of those objset files).

I'd suggest taking this implementation and closing #3

**Comment by Freaky** [comment]
I mostly use Ruby for scripting, probably helps explain the style - hopefully it's not *too* terse, I'm not trying to make it compact for the sake of it.

@adriaandegroot certainly has the more conservative approach, which is no bad thing if it's easier for others to understand/maintain.

**Comment by jimsalterjrs** [comment]
Since @adriaandegroot is the competitor and likes this one better, I'm going with this one. Thanks both!

**Pull request merged**
