### PR TITLE
Add a -z flag to suppress datasets with no activity

### LINKED ISSUE #12: RFE to add -z
Very nice tool!

This is a request to mimic iostat -z and omit output for datasets with no activity during the sample period. The workaround is simple, grep -v "0.00       0.00       0.00       0.00       0.00       0.00", but I think should would be nice to support directly.

### PR DESCRIPTION
**Pull request by Freaky**
Fixes #12

This feels best combined with -s name, as the multi-line naming gets a bit too dynamic.

### CODE REVIEW

**Comment by Freaky** [comment]
Thoughts on making -s name default in this mode?

**Comment by jimsalterjrs** [comment]
Hmmm, there appears to have been a bug in this PR, if you tested after I merged all the others today:

~~~~
me@banshee:/usr/local/bin$ sudo ioztat
  File "/usr/local/bin/ioztat", line 68
    header, _fieldnames, *fields = [line.split() for line in f]
                         ^
SyntaxError: invalid syntax
~~~~

**Comment by jimsalterjrs** [comment]
well, it doesn't appear to have been this one--I'm seeing the breakage after reverting this as well.

**Comment by jimsalterjrs** [comment]
@Freaky I don't think I have much of an opinion about using `-s name` by default when `-z` is on. That seems fine to me. I suppose the question is whether people who want to opt out can specify a `-s` argument that brings back the default sorting?

Assuming the answer to the latter is "yes" I'd say you can go ahead and change the default sort when `-z` is on.

**Pull request merged**
