### PR TITLE
Overwrite old reports in terminal by default

### PR DESCRIPTION
**Pull request by Aluminite**
I thought that this script put a little too much into the terminal. This PR makes it so that only the most recent report is visible, which can be disabled with the new `-n` argument.

### CODE REVIEW

**Comment by jimsalterjrs** [comment]
@Aluminite am I reading this correctly, that you used `-n` as an argument to specify old-style batch-mode continuous scroll printing?

That's not going to work because it conflicts with @Freaky's `-n` for dataset literals. I'm open to suggestions from the both of you for the best arguments for each improvement that don't conflict; I'm not too picky aside from wanting to default to "as much like system iostat arguments as possible."

**Comment by Freaky** [comment]
This seems unusual behaviour for an iostat command - at the very least it should be opt-in instead of opt-out IMO.

This approach is also a bit too naive and doesn't cope with the number of datasets going down.

**Comment by jimsalterjrs** [comment]
I quite like the idea of not _having_ to use GNU watch to get an inplace display, but I don't really have a dog in the fight about whether it should be opt-in or opt-out.

**Comment by jimsalterjrs** [comment]
Thanks @Aluminite , good stuff. Would you also add a keypress check, and exit if the user presses "q" while in `-o` mode, please?

**Pull request merged**
