### PR TITLE
Rework formatting

### LINKED ISSUE #23: Output is insensitive to terminal width
The current output width is 106 columns, which by happy coincidence is precisely the width of my usual terminals.

This coincidence seems unlikely to be universal, and some sensitivity to this would seem to be in order.

### PR DESCRIPTION
**Pull request by Freaky**
This makes ioztat output more closely resemble `zpool iostat`:

```
                              operations      bandwidth         opsize
dataset                       read   write    read   write    read   write
--------------------------  ------  ------  ------  ------  ------  ------
rpool
   ROOT
      default                   23       0   62.6K       0    2.7K     759
   cvs                           0       0    1.6K     892   24.2K  108.4K
   home                          0       0       0       0       0       0
      freaky                     3       2   29.7K    8.3K   10.2K    3.9K
```

This also adds `-e` for exact values (`-p` in zpool iostat, which we're currently using elsewhere) and `-H` for scripted mode that drops the header and separates fields by tabs.

The intent is for this to eventually fix #23, probably by adjusting the space for dataset.

### CODE REVIEW

**Comment by Freaky** [comment]
Further following on from copying `zpool iostat`, we precalculate the largest name width needed, and per #23 clamp it to the width of the terminal.  This is updated each iteration.

**Comment by Freaky** [comment]
This really needs its tires kicking before I'd be happy to release it anywhere, but it's progressed enough for people to actually do that while expecting it all to work.

The output format has completely changed, and the way output is handled has almost completely changed, with a brand new `ColumnFormatter` dealing with most of it.  There are also some new flags primarily oriented to scripting use which make the output more parseable.  These big user-facing changes I think justifies a major version bump.

Terminal widths are now handled gracefully, with dataset names being abbreviated to fit when necessary.  The header is now repeated on a schedule based on terminal height in a similar manner to zpool-iostat.

**Comment by jimsalterjrs** [comment]
Ready to merge into main, but not to base a release around then?

**Comment by jimsalterjrs** [comment]
Hmm. Any idea why it's so screen-tear-y compared to, eg, `watch -n1 ioztat -y -c1` ?

**Comment by jimsalterjrs** [comment]
also, while I'm nitpicking: the "bandwidth" column header really ought to be "throughput."

**Comment by Freaky** [comment]
GNU watch uses curses, so it's probably a lot smarter in how it updates the display.  Not sure if this can be easily emulated with a few control codes or if we'd need to use curses for that too.  It is part of Python stdlib...

I went with bandwidth because that's the same term zpool-iostat uses for those columns.  Is there a good reason to diverge?

**Comment by Freaky** [comment]
That appears to help, printing each update in one go instead of line by line.

**Comment by Freaky** [comment]
Could further copy gnu-watch behaviour by stopping once we've printed enough lines to fill the terminal.

**Comment by jimsalterjrs** [comment]
"Bandwidth" just isn't technically correct for what it's measuring. I'm not sure why some people got started calling throughput "bandwidth" in the first place.

An RF signal has "bandwidth" meaning the amount of spectrum the signal occupies... which still doesn't mean anything directly about throughput, since it doesn't tell you anything about the modulation frequency. It's even less applicable when talking about storage throughput, since there's no RF spectrum involved at all. It's sort of like calling the clock speed button on oldschool PCs "turbo"--no, that button does not increase oxygen pressure in the PC's motor by forcing its exhaust through a compressor turbine! :)

**Comment by jimsalterjrs** [comment]
Can confirm, no longer seeing screen tear since your last updates. (Possibly worth noting: I'm running it over SSH, not locally--screen tear might be more noticeable that way, idk.)

**Comment by Freaky** [comment]
People got used to using "bandwidth" for "data per second" the same way they got used to "turbo" meaning "make go fast" and "broadband" meaning "not dialup".  Language evolves and mutates.

Whether we want to support this particular mutation or not... shrug.  I just copied zpool.  It's easy enough to change.

Other bikeshed question is if the `bytes`/`io` sort options should follow the group headings and be `operations` and `bandwidth`/`throughput`.

**Comment by Freaky** [comment]
Let's merge this, we can deal with any remaining issues as needed.

**Pull request merged**
